---
title: "Report Omni Reproducible Cell Analysis"
date: "`r Sys.Date()`"
output: pdf_document
params:
   ResultList: x
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(DT)
ResultList = parmsList$ResultList

isEmptyOrNoninformative <- function(df) {
  if (is.null(df) || nrow(df) == 0) {
    return(TRUE)
  }
  all(sapply(df, function(column) all(column == "-")))
}
```

```{r elisa-data, echo=FALSE, results='asis'}
if (!is.null(ResultList$elisaResult[["TablePlot"]])) {
  cat("### ELISA\n\n")
  cat("#### Initial Data\n\n")
  DT::datatable(ResultList$elisaResult[["TablePlot"]])
}
```

```{r regression-analysis, echo=FALSE, results='asis'}
if (!is.null(ResultList$elisaResult[["Regression"]]$data)) {
  cat("### Regression Analysis\n\n")
  cat("#### Table of Standard Curve\n\n")
  DT::datatable(ResultList$elisaResult[["Tablestandcurve"]])
  
  cat("#### Regression Data\n\n")
  DT::datatable(ResultList$elisaResult[["Regression"]]$data)

  cat("#### Regression Plot\n\n")
  print(ResultList$elisaResult[["Regression"]]$plot)
}
```


```{r elisa-analysis, echo=FALSE, results='asis'}
if (!is.null(ResultList$elisaResult[["dataFinal"]])) {
  cat("### Analysis\n\n")
  DT::datatable(ResultList$elisaResult[["dataFinal"]])

  # Plotting if dataFinal is not null
  print(ggplot(ResultList$elisaResult[["dataFinal"]],
               aes(x = Time, y = Quantification, fill = Experiment, group = Experiment)) +
        geom_bar(position = "dodge", stat = "identity") +
        theme_bw() +
        labs(x = "Time", y = "Average quantifications obtained\n from the lm"))
}
```


```{r cytotoxicity-section, echo=FALSE, results='asis'}
if (!is.null(ResultList$cytotoxResult[["TablePlot"]]) || !is.null(ResultList$cytotoxResult[["data"]])) {
  cat("## Cytotoxicity\n\n")
  cat("### Initial Data\n\n")
  DT::datatable(ResultList$cytotoxResult[["TablePlot"]])

  if (!is.null(ResultList$cytotoxResult[["data"]])) {
    cat("### Analysis\n\n")
    print(ggplot(ResultList$cytotoxResult[["data"]],
                 aes(x = as.factor(EXP), y = Res, fill = SN, col = SN),
                 alpha = 0.4) +
          geom_boxplot() +
          theme_bw() +
          labs(x = "Experimental condition", y = "% Values w.r.t \nthe baseline cell death",
               col = "Sample Name", fill = "Sample Name"))
  }
}

```


```{r endocytosis-section, echo=FALSE, results='asis'}
if (!is.null(ResultList$endocResult[["TablePlot"]]) || !is.null(ResultList$endocResult[["dataFinal"]])) {
  cat("## Endocytosis\n\n")
  cat("### Initial Data\n\n")
  DT::datatable(ResultList$endocResult[["TablePlot"]])

  if (!is.null(ResultList$endocResult[["dataFinal"]])) {
    cat("### Analysis\n\n")
    DT::datatable(ResultList$endocResult[["dataFinal"]])
  }
}
```


```{r rt-qpcr-section, echo=FALSE, results='asis'}
if (!is.null(ResultList$pcrResult[["Initdata"]]) || !is.null(ResultList$pcrResult[["NewPCR"]])) {
  cat("## RT-qPCR\n\n")
  cat("### Initial Data\n\n")
  DT::datatable(ResultList$pcrResult[["Initdata"]])

  cat("### Normalization on Housekeeping Genes\n\n")
  if (!is.null(ResultList$pcrResult[["NewPCR"]])) {
    DT::datatable(ResultList$pcrResult[["NewPCR"]])
    print(ResultList$pcrResult[["plotPRC"]])
  }
}

```

<!-- ### Comp Analysis -->

<!-- ```{r, echo=FALSE} -->

<!-- ResultList$pcrResult[["CompPRC"]] -->

<!-- ggplot(data =  ResultList$pcrResult[["CompPRC"]], -->
<!--                   aes(x= Gene, y = Qnorm, fill = Sample)) +  -->
<!--              facet_wrap(~Norm, ncol = 1) + -->
<!--              geom_bar(stat = "identity",position = "dodge") -->


<!-- ``` -->

```{r wb-section, echo=FALSE, results='asis'}
if (!is.null(ResultList$wbResult[["Im"]])) {
  cat("## WB\n\n")
  cat("### Initial Data\n\n")
  # Assumiamo che ResultList$wbResult[["Im"]] sia un oggetto che contiene i dati dell'immagine
  # Se ResultList$wbResult[["Im"]] è un percorso file, dovresti caricarlo, o se è un oggetto immagine, usalo direttamente
  ListIm <- ResultList$wbResult[["Im"]]
  im <- ListIm$RGB  # Assumendo che ListIm$RGB sia l'immagine pronta da mostrare
  
  # Verifica che 'im' sia definito correttamente e non sia null
  if (!is.null(im)) {
    plot(c(1, dim(im)[2]), c(1, dim(im)[1]), type = 'n', ann = FALSE)
    rasterImage(im, 1, 1, dim(im)[2], dim(im)[1])
  } else {
    cat("No image data available.\n")
  }
}

if (!is.null(ResultList$wbResult[["Plots"]])) {
  cat("### Analysis\n\n")
  print(ResultList$wbResult[["Plots"]] + labs(title = "Initial curve"))
}

if (!is.null(ResultList$wbResult[["TruncatedPlots"]])) {
  print(ResultList$wbResult[["TruncatedPlots"]] + labs(title = "Truncated curve"))
}

if (!is.null(ResultList$wbResult[["AUCdf"]])) {
  DT::datatable(ResultList$wbResult[["AUCdf"]])
}

```

```{r wb-comparison-section, echo=FALSE, results='asis'}
if (!isEmptyOrNoninformative(ResultList$wbquantResult[["NormWBanalysis_filtered"]]) ||
    !isEmptyOrNoninformative(ResultList$wbquantResult[["WBanalysis_filtered"]]) ||
    !isEmptyOrNoninformative(ResultList$wbquantResult[["RelDensitiy"]]) ||
    !isEmptyOrNoninformative(ResultList$wbquantResult[["AdjRelDensitiy"]])) {
  cat("## WB Comparison\n\n")
  
  cat("### Normalizer WB\n\n")
  if (!isEmptyOrNoninformative(ResultList$wbquantResult[["NormWBanalysis_filtered"]])) {
    DT::datatable(ResultList$wbquantResult[["NormWBanalysis_filtered"]])
  }
  
  cat("### WB Analysis\n\n")
  if (!isEmptyOrNoninformative(ResultList$wbquantResult[["WBanalysis_filtered"]])) {
    DT::datatable(ResultList$wbquantResult[["WBanalysis_filtered"]])
  }

  cat("### Densities\n\n")
  if (!isEmptyOrNoninformative(ResultList$wbquantResult[["RelDensitiy"]])) {
    DT::datatable(ResultList$wbquantResult[["RelDensitiy"]])
  }
  
  if (!isEmptyOrNoninformative(ResultList$wbquantResult[["AdjRelDensitiy"]])) {
    DT::datatable(ResultList$wbquantResult[["AdjRelDensitiy"]])
  }
}
```



